name: called2.yml
run-name: called2.yml
on:
  workflow_call:
    inputs:
      input1:
        description: input1
        type: string
        required: true
      input2:
        description: input2
        type: string
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{inputs.input1}} ${{inputs.input2}}"
