name: caller2
run-name: caller2
on: push
jobs:
  job1:
    uses: ./.github/workflows/called2.yml
    with:
      input1: "sandeep"
      input2: "mishra"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: display_outputs
        run: |
          echo ${{needs.jobs1.outputs.out1}}
          echo ${{needs.jobs1.outputs.out2}}
