name: outputs_ex
run-name: outputs_ex
on: 
  workflow_dispatch:
    inputs:
      env_type:
        description: environment type
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
jobs:
  job1:
    environment: ${{ inputs.env_type }}
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.key1 }}
      output2: ${{ steps.step2.outputs.key2 }}
    steps:
      - id: step1
        run: echo "key1=value1" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "key2=value2" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    environment: ${{ inputs.env_type }}
    runs-on: ubuntu-latest
    steps:
      - run: echo values for key1 and key2 are ${{ needs.job1.outputs.output1 }}, ${{ needs.job1.outputs.output2 }} resp. 
    
        
  
    
