name: upload&download_ex
run-name: upload&download_ex
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: expr 9 \* 9 > multiply.txt
      - uses: actions/upload-artifact@v4
        with:
          name: multiply
          path: multiply.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: multiply
      - shell: bash
        run: |
          value=$(cat multiply.txt)
          expr $value + 9 > final.txt
      - uses: actions/upload-artifact@v4
        with:
          name: final
          path: final.txt
  job3: 
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: final
      - run: cat final.txt
   
          
